builds:
  - main: ./cmd/pomodoro
    binary: pomodoro
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/open-pomodoro/openpomodoro-cli/cmd.Tag={{.Tag}}
    goos:
      - darwin
      - linux
      - windows
